# Generated by Django 3.1.4 on 2020-12-12 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201208_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('pk',), 'verbose_name': 'Имя параметра', 'verbose_name_plural': 'Список всех параметров'},
        ),
        migrations.AlterField(
            model_name='itemparameter',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_parameters', to='app.iteminfo', verbose_name='Информация о продукте'),
        ),
    ]
