# Generated by Django 3.1.4 on 2020-12-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201214_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='item',
            new_name='itemInfo',
        ),
    ]
