# Generated by Django 3.1.4 on 2020-12-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201215_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='itemInfo',
            new_name='item_info',
        ),
    ]
